FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 2316

# Lancer la CLI gwsetup
CMD ["python", "-m", "geneweb.gwsetup"]
