name: 🔄 Auto Sync main → preprod

on:
  push:
    branches:
      - main   # dès qu'il y a un commit/merge sur main

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: 📦 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔄 Create pull request main → preprod
        id: sync
        uses: peter-evans/create-pull-request@v6
        with:
          base: preprod
          branch: main
          title: "🔄 Sync main → preprod"
          body: |
            Automatic synchronization from **main** to **preprod**.
            (Triggered by a push on main)
          labels: auto-sync
          commit-message: "chore(sync): merge main into preprod"
          draft: false
          delete-branch: false
          reviewers: |
            NoahTesson 
          assignees: |
            NoahTesson

      - name: ✅ Auto-approve the PR
        if: steps.sync.outputs.pull-request-url != ''
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 🚀 Auto-merge the PR
        if: steps.sync.outputs.pull-request-url != ''
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: merge
