name: Tests geneweb

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
    build:
        name: Launch python tests
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./geneweb-python
        
        env:
          PYTHON_VERSION: "3.10"
          TEST_DIR: tests/

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python ${{ env.PYTHON_VERSION }}
              uses: actions/setup-python@v4
              with:
                python-version: '${{ env.PYTHON_VERSION }}'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r ${{ env.TEST_DIR }}requirements.txt

            - name: Lint with Ruff
              run: |
                pip install ruff
                ruff check ${{ env.TEST_DIR }} --target-version py310
              continue-on-error: true
      
            - name: Test with pytest
              run: |
                pip install pytest coverage
                coverage run -m pytest -v -s

            - name: Generate Coverage Report
              run: |
                coverage report -m
