name: Tests geneweb

    #pull_request:
        #types: [closed]
        
on:
    workflow_dispatch:

jobs:
    build:
        #if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./geneweb-python
        
        env:
          PYTHON_VERSION: 3.10
          TEST_DIR: tests/

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python $PYTHON_VERSION
              uses: actions/setup-python@v4
              with:
                python-version: '$PYTHON_VERSION'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r $TEST_DIRrequirements.txt

            - name: Lint with Ruff
              run: |
                pip install ruff
                ruff check $TEST_DIR --target-version py310
              continue-on-error: true
      
            - name: Test with pytest
              run: |
                pip install pytest coverage
                coverage run -m pytest -v -s

            - name: Generate Coverage Report
              run: |
                coverage report -m
