name: Tests geneweb

    #pull_request:
        #types: [closed]
on:
    workflow_dispatch:

jobs:
    build:
        #if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./geneweb-python

        strategy:
            matrix:
                python-version: ["3.10"]
                tests-folder: ["tests/"]

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                python-version: '${{ matrix.python-version }}'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r ${{ matrix.tests-folder }}requirements.txt

            - name: Lint with Ruff
              run: |
                pip install ruff
                ruff check ${{ matrix.tests-folder }} --target-version py310 --format github
              continue-on-error: true
      
            - name: Test with pytest
              run: |
                pip install pytest
                coverage run -m pytest -v -s

            - name: Generate Coverage Report
              run: |
                coverage report -m
