name: Create Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set release version
        id: vars
        run: |
          VERSION="v$(date +'%Y.%m.%d.%H%M')"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh

      - name: Create GitHub Release
        run: |
          gh release create ${{ env.VERSION }} \
            --title "Release ${{ env.VERSION }}" \
            --notes "Automated release from main branch" \
            --target main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
